### ISSUE TITLE
Add querystring option to WebACS URL to autoConnect to ARE

### ISSUE THREAD

**Issue by deinhofer** [asterics/WebACS#12]
If the WebACS is hosted by the ARE and loaded from that it would be handy, if the user could specify a URL to automatically connect to the ARE when loading the page.

This way, the ARE GUI could provide a feature to open and autoconnect the WebACS by a gui button and shortcut.

e.g. http://localhost:8081/webapps/WebACS/?autoConnect=true

**Comment by kingcole** [comment]
The WebACS already auto-connects to the ARE it is hosted from - so what's the point in adding a querystring option for that?

**Comment by deinhofer** [comment]
Just in case if somebody does not want that behaviour. But not a high priority.
