### ISSUE TITLE
Add queryString to WebACS URL to auto download component collection from ARE

### ISSUE THREAD

**Issue by deinhofer** [asterics/WebACS#13]
If the WebACS is hosted by the ARE and loaded from that it would be handy, if the user could specify a URL to automatically download the component collection from the ARE when connecting to the ARE.

This way, the ARE GUI could provide a feature to open and autoconnect the WebACS by a gui button and shortcut.

e.g. http://localhost:8081/webapps/WebACS/?autoConnect=true&autoDownloadComponentCollection=true

if the option is not specified, default should be true.

**Comment by kingcole** [comment]
The WebACS already uses the ARE's componentCollection as default, if it's hosted as ARE-webservice.

**Comment by deinhofer** [comment]
ok sounds good, I just recognized that I did not git pull and so missed some recent updates.
