### ISSUE TITLE
Start-Pause-Stop not in sync with ARE.

### ISSUE THREAD

**Issue by sabicalija** [asterics/WebACS#20]
Button to Play-Pause-Stop are WebACS functional and not in sync with execution state in ARE (see screenshot).

![image](https://user-images.githubusercontent.com/13609768/36487714-e16469b0-1721-11e8-8de0-9648f33c6cfa.png)

**Comment by deinhofer** [comment]
Is there a way how to reproduce it?

**Comment by sabicalija** [comment]
Sorry, was a misunderstanding. I'm closing this issue.

I misunderstood the icons somehow. :) It appeared to me, that the icons in the red rectangle mean that the ARE was stopped, because that was the highlighted icon. But actually it means that these two buttons (pause, stop) are the only reasonable icon to press.
