### ISSUE TITLE
drop down menu missing in knx-component properties

### ISSUE THREAD

**Issue by ghost** [asterics/WebACS#26]
In WebACS the drop-down menu in the DPTEvent fields of the KNX component properties is missing (see screenshot). 

![dropdown_missing](https://user-images.githubusercontent.com/10290425/36663427-d2a33c30-1ae1-11e8-993d-15164fb04169.png)

Way to reproduce:
add KNX component to the model and take a look at the properties.

**Comment by ChrisVeigl** [comment]
This issue affects not only the KNX component, but all components which have "dynamic properties" - the dropdown selection boxes with runtime-generated values from the ARE. 

The dynamic properties are not yet supported in the WebACS, see:
https://github.com/asterics/WebACS/issues/18

**Comment by ChrisVeigl** [comment]
actually this is an important one because several pulgins cannot be used properly in the WebACS without the dynaminc property feature....  - should we increase the priority of #18 and assign somebody who could take care for that ?

**Comment by deinhofer** [comment]
nevertheless it's a duplicate so let's close it and priorize #18
