### ISSUE TITLE
Arduino Events not displayed in EventVisualizer.

### ISSUE THREAD

**Issue by sabicalija** [asterics/WebACS#29]
Tested ArduinoDigitalOutput on my Ubuntu 16.04.3 (virtualbox 5.2.6 r120293, VBoxGuestAdditions_5.2.7-120528).

When connecting event output of Arduino Microcontroller, no events are displayed in the EventVisualizer.

![image](https://user-images.githubusercontent.com/13609768/37244300-2f43151a-2487-11e8-8251-4215be6bba8b.png)

The events from ButtonGrid are displayed correctly, and the connected LED on Digital Output 2 is lighting (-> Pin2 is set, and reset correctly).

![image](https://user-images.githubusercontent.com/13609768/37244315-7455af8c-2487-11e8-8c60-5d7c1ae162bf.png)

I've tried also to connect only events from Arduino and removed the connection with the ButtonGrid.

But still, the LED is lighting/not lighting as desired, but no output in the EventVisualizer.

![image](https://user-images.githubusercontent.com/13609768/37244330-b0271960-2487-11e8-8857-2e93ff03992a.png)

**Comment by ChrisVeigl** [comment]
in the current version of the Arduino CIM firmware, pinChange events are only available for input pins (eg. pinMode property set to "input with pullup" for measuring GPIO input voltage levels). When you configure the pin in output mode it is assumed that you control the pin voltage from other sources / events. 
If firing pinChange events for output pins is desired, this must be implemented in the CIM firmware

**Comment by sabicalija** [comment]
Would it be possible to remove the events that are not supported to avoid misunderstandings in future?
