### ISSUE TITLE
Tab switch between models fires many events and is slow

### ISSUE THREAD

**Issue by deinhofer** [asterics/WebACS#39]
If you have several models opened in the WebACS and click on another model tab within the webacs to switch to the other model, many javascript events are fired, see:

**Switching tab**
![image](https://user-images.githubusercontent.com/4621810/57527458-0c177880-7330-11e9-8620-242de055aac7.png)

**Web console with Javascript events**

![Selection_090](https://user-images.githubusercontent.com/4621810/57527481-1afe2b00-7330-11e9-9707-eaca2eaf931d.png)

This also leads to many requests to the ARE, as can be seen in the debugging output of the ARE:

![image](https://user-images.githubusercontent.com/4621810/57527569-4da82380-7330-11e9-8553-3c37149ba8b5.png)

This slows down the switching tremendously!!

Maybe this is also the reason why the webacs is very slow on low-powered PCs?

**Comment by klues** [comment]
PR #47 should fix it. Please test and merge.
