### ISSUE TITLE
Keyboard shortcuts not working

### ISSUE THREAD

**Issue by deinhofer** [asterics/WebACS#44]
The keyboard shortcuts in the top bar of the WebACS don't work any more:
![image](https://user-images.githubusercontent.com/4621810/67862130-da82ab80-fb21-11e9-8166-102d0dd5c4a6.png)

Additionally, the typical keyboard shortcuts for copy, paste, duplicate, delete don't work.

## Solution

Use new ```event.key``` notation: https://stackoverflow.com/questions/35394937/keyboardevent-keycode-deprecated-what-does-this-mean-in-practice

**Comment by klues** [comment]
keyboard shortcuts like Ctrl+C and Ctrl+V also do not work on the current webacs.asterics.eu

PR #46 should fix the biggest problems:
* keyboard shortcuts of the top bar are working
* other keyboard shortcuts are working (see https://github.com/asterics/WebACS/blob/96f853a3a97ef7beac9f9e267783e560add01a03/view/view.js#L261 ): 
    * Delete
    * F1 -> Help
    * Ctrl+X -> Cut
    * Ctrl+C -> Copy
    * Ctrl+V -> Paste
    * Ctrl+Z -> Undo
    * Ctrl+Y -> Redo
    * Ctrl+D -> Drop channel

Moreover the "keyboard mode" (which I've never heard before) now also seems to work:
* Select an element
* Press "Enter" to enter "keyboard mode"
* use arrow keys to navigate through elements
* use Shift + arrow keys to move elements by keyboard

I've tested everything in latest Firefox, Chrome and Edge. "Keyboard mode" does not work in Edge, all other things are working fine.

**Comment by klues** [comment]
Someone should test the changes on macOs/Safari.

**Comment by deinhofer** [comment]
Thanks for the fix. That was very fast :-)
