### ISSUE TITLE
Download Component Collection not working

### ISSUE THREAD

**Issue by ChrisVeigl** [asterics/WebACS#5]
When downloading the Component Collection from the connected ARE, it seems that the new component descriptions are not fully applied. For example there is still a mismatch detected in the Cellboard plugin when the default (autostart) model is loaded from the ARE right after the Component Collection has been updated.

(however the other components like the LipMouse plugin show updates correctly) 

It would be desireable to use the currently installed components of the ARE as the default Component Collection if the WebACS is hosted from the ARE webserver - so that updating the collection becomes obsolete in this case.

Testing environment:
platform: RaspberryPi 3
OS: Ubuntu Mate 16.04
browser: Mozilla Firefox 52.02

**Comment by kingcole** [comment]
These are actually 2 issues - have opened second part in separate issue.

**Comment by deinhofer** [comment]
Thanks!
Reopened this one again because the first part is not fixed either.

**Comment by kingcole** [comment]
works for me - what problems do you still have??

**Comment by deinhofer** [comment]
Just tested it again.
When you do "Download Component Collection"  and then "Download Model" with the autostart model of the ARE. The CellBoard plugin mismatch does not exist any more. But if you click on "New Model" the new component collection is lost again. Downloading the autostart model produces the Cellboard error again.
Maybe this is also the same for "Open Model". Maybe just an old reference anywhere?

At the end, please also add the current the component collection as default component collection to th e WebACS.

**Comment by kingcole** [comment]
Every model has it's own componentCollection in the WebACS - a new model is created with the default. It has been decided to be this way to be "future-proof" (there will be a functionality to load componentCollections from a file some day and then it makes sense to have one for each model when e.g. working for different clients and copying between files). So, in other words, it's not a bug, it's a feature ;)
